CREATE TABLE IF NOT EXISTS "Supplies" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp with time zone NOT NULL,
    "PartyType" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "Description" text NULL,
    "UserId" bigint NOT NULL,
    "CurrencyId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedBy" text NULL,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Supplies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Supplies_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Supplies_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

ALTER TABLE "Supplies" DROP COLUMN IF EXISTS "Quantity";
ALTER TABLE "Supplies" DROP COLUMN IF EXISTS "SemiProductId";
ALTER TABLE "Supplies" DROP COLUMN IF EXISTS "ContainerCount";
ALTER TABLE "Supplies" DROP COLUMN IF EXISTS "PricePerContainer";
ALTER TABLE "Supplies" DROP COLUMN IF EXISTS "ExchangeRate";

CREATE INDEX IF NOT EXISTS "IX_Supplies_CurrencyId" ON "Supplies" ("CurrencyId");
CREATE INDEX IF NOT EXISTS "IX_Supplies_UserId" ON "Supplies" ("UserId");

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260615163341_AddSupplies', '9.0.9'
WHERE NOT EXISTS (
    SELECT 1
    FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260615163341_AddSupplies'
);
