-- =============================================================================
-- Forex — eski bazani dasturning joriy versiyasiga moslash
-- Sana: 2026-06-23
-- =============================================================================
-- Bu skript eski production bazaning sxemasini loyihaning HOZIRGI holatiga
-- to'liq moslaydi. Eski backup va joriy EF modeli dasturiy taqqoslandi —
-- quyidagi 3 ta o'zgarishdan boshqa farq yo'q (qolgan barcha jadvallar bir xil).
--
--   1. 11 ta ishlatilmaydigan (bo'sh) jadval o'chiriladi.
--   2. Yangi "Supplies" jadvali yaratiladi (ta'minotchi/vositachi moliyaviy hisobi).
--   3. "OperationRecords" ga "UserId" va "SupplyId" ustunlari qo'shiladi (nullable).
--
-- Ishlatish:
--   1. Production bazani to'liq backup qiling.
--   2. Backup nusxasi yoki to'g'ridan baza ustida shu skriptni bir marta ishga tushiring.
--   Skript bitta tranzaksiyada — xato bo'lsa hammasi bekor qilinadi.
--
-- Eslatma: "__EFMigrationsHistory" ga tegilmaydi. Agar siz migratsiyani qaytadan
-- generatsiya qilsangiz, EF history'ni o'zi boshqaradi.
-- =============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. Ishlatilmaydigan jadvallarni o'chirish (hammasi bo'sh; CASCADE — FK'larni ham olib tashlaydi)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS "EntryToProcesses"    CASCADE;
DROP TABLE IF EXISTS "InProcesses"         CASCADE;
DROP TABLE IF EXISTS "WorkerPayments"      CASCADE;
DROP TABLE IF EXISTS "ProductionStages"    CASCADE;
DROP TABLE IF EXISTS "ProductionBatches"   CASCADE;
DROP TABLE IF EXISTS "InvoicePayments"     CASCADE;
DROP TABLE IF EXISTS "SemiProductEntries"  CASCADE;
DROP TABLE IF EXISTS "SemiProductResidues" CASCADE;
DROP TABLE IF EXISTS "Invoices"            CASCADE;
DROP TABLE IF EXISTS "ProductTypeItems"    CASCADE;
DROP TABLE IF EXISTS "Manufactories"       CASCADE;

-- ----------------------------------------------------------------------------
-- 2. Yangi "Supplies" jadvali (ta'minotchi/vositachi moliyaviy hisobi)
--    PartyType: 0 = Ta'minotchi, 1 = Vositachi
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Supplies" (
    "Id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "Date"        timestamp with time zone NOT NULL,
    "PartyType"   integer NOT NULL,
    "Amount"      numeric NOT NULL,
    "Description" text,
    "UserId"      bigint NOT NULL,
    "CurrencyId"  bigint NOT NULL,
    "CreatedAt"   timestamp with time zone NOT NULL,
    "CreatedBy"   text,
    "UpdatedAt"   timestamp with time zone,
    "UpdatedBy"   text,
    "IsDeleted"   boolean NOT NULL,
    CONSTRAINT "PK_Supplies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Supplies_Currencies_CurrencyId"
        FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Supplies_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_Supplies_CurrencyId" ON "Supplies" ("CurrencyId");
CREATE INDEX IF NOT EXISTS "IX_Supplies_UserId"     ON "Supplies" ("UserId");

-- ----------------------------------------------------------------------------
-- 3. "OperationRecords" ga yangi ustunlar (ikkalasi ham nullable — eski qatorlar NULL bo'ladi)
-- ----------------------------------------------------------------------------
ALTER TABLE "OperationRecords" ADD COLUMN IF NOT EXISTS "UserId"   bigint;
ALTER TABLE "OperationRecords" ADD COLUMN IF NOT EXISTS "SupplyId" bigint;

ALTER TABLE "OperationRecords"
    ADD CONSTRAINT "FK_OperationRecords_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "OperationRecords"
    ADD CONSTRAINT "FK_OperationRecords_Supplies_SupplyId"
        FOREIGN KEY ("SupplyId") REFERENCES "Supplies" ("Id");

CREATE INDEX IF NOT EXISTS "IX_OperationRecords_SupplyId" ON "OperationRecords" ("SupplyId");
CREATE INDEX IF NOT EXISTS "IX_OperationRecords_UserId"   ON "OperationRecords" ("UserId");

COMMIT;
