-- =============================================================================
-- Forex — ESKI BACKUP holatidan joriy (multicurrency) holatga YAXLIT moslash
-- =============================================================================
-- Bu skript `db_backup.sql` dagi eski sxemani loyihaning HOZIRGI holatiga bir o'tishda
-- keltiradi: jadval tozalash + Supplies + OperationRecords ustunlari + multicurrency
-- (har userga asosiy valyuta) + backfill + balanslarni qayta qurish.
--
-- Bosqichlar:
--   A. 11 ta ishlatilmaydigan jadvalni o'chirish.
--   B. "Supplies" jadvali; "OperationRecords" ga "UserId"/"SupplyId".
--   C. Multicurrency ustunlari: "Users"."SettlementCurrencyId",
--      "OperationRecords"."CurrencyId" va "Rate", "Sales"."CurrencyId" va "BaseAmount".
--   D. Backfill: OperationRecords.UserId (Sale/Transaction'dan), asosiy valyuta (rol bo'yicha),
--      original valyuta + kurs; eski Sale bug'i (CurrencyId=0); Sales.BaseAmount (so'm ekvivalenti).
--   E. FK + index + NOT NULL.
--   F. Balanslarni qayta qurish (settlement valyutada).
--   G. "Returns"/"ReturnItems" jadvallari (mahsulot qaytarish / credit note).
--      OperationType.Return = 4 — bu INTEGER, shuning uchun mavjud jadvallarga o'zgarish kerak emas.
--
-- Ishlatish:
--   1. `db_backup.sql` ni toza bazaga tiklang.
--   2. Shu skriptni bir marta ishga tushiring (bitta tranzaksiya, qayta ishga tushsa ham xavfsiz).
--   3. Dollar bilan ishlovchi maxsus MIJOZLARNI (Mijoz rolida, lekin USD) qo'lda belgilang:
--        UPDATE "Users" SET "SettlementCurrencyId" = (SELECT "Id" FROM "Currencies" WHERE "Code"='USD')
--        WHERE "Id" IN (...);
--      so'ng shu skriptning F bo'limini qayta ishga tushiring.
--
-- "__EFMigrationsHistory" ga tegilmaydi.
-- UserRole: User=0, Taminotchi=1, Mijoz=2, Hodim=3, Vositachi=4.
-- =============================================================================

BEGIN;

-- ============================================================================
-- A. Ishlatilmaydigan (bo'sh) jadvallarni o'chirish
-- ============================================================================
DROP TABLE IF EXISTS "EntryToProcesses"    CASCADE;
DROP TABLE IF EXISTS "InProcesses"         CASCADE;
DROP TABLE IF EXISTS "WorkerPayments"      CASCADE;
DROP TABLE IF EXISTS "ProductionStages"    CASCADE;
DROP TABLE IF EXISTS "ProductionBatches"   CASCADE;
DROP TABLE IF EXISTS "InvoicePayments"     CASCADE;
DROP TABLE IF EXISTS "SemiProductEntries"  CASCADE;
DROP TABLE IF EXISTS "SemiProductResidues" CASCADE;
DROP TABLE IF EXISTS "Invoices"            CASCADE;
DROP TABLE IF EXISTS "ProductTypeItems"    CASCADE;
DROP TABLE IF EXISTS "Manufactories"       CASCADE;

-- ============================================================================
-- B. "Supplies" jadvali + "OperationRecords" ga UserId/SupplyId
-- ============================================================================
CREATE TABLE IF NOT EXISTS "Supplies" (
    "Id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "Date"        timestamp with time zone NOT NULL,
    "PartyType"   integer NOT NULL,
    "Amount"      numeric NOT NULL,
    "Description" text,
    "UserId"      bigint NOT NULL,
    "CurrencyId"  bigint NOT NULL,
    "CreatedAt"   timestamp with time zone NOT NULL,
    "CreatedBy"   text,
    "UpdatedAt"   timestamp with time zone,
    "UpdatedBy"   text,
    "IsDeleted"   boolean NOT NULL,
    CONSTRAINT "PK_Supplies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Supplies_Currencies_CurrencyId"
        FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Supplies_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_Supplies_CurrencyId" ON "Supplies" ("CurrencyId");
CREATE INDEX IF NOT EXISTS "IX_Supplies_UserId"     ON "Supplies" ("UserId");

ALTER TABLE "OperationRecords" ADD COLUMN IF NOT EXISTS "UserId"   bigint;
ALTER TABLE "OperationRecords" ADD COLUMN IF NOT EXISTS "SupplyId" bigint;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_OperationRecords_Users_UserId') THEN
        ALTER TABLE "OperationRecords"
            ADD CONSTRAINT "FK_OperationRecords_Users_UserId"
            FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_OperationRecords_Supplies_SupplyId') THEN
        ALTER TABLE "OperationRecords"
            ADD CONSTRAINT "FK_OperationRecords_Supplies_SupplyId"
            FOREIGN KEY ("SupplyId") REFERENCES "Supplies" ("Id");
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_OperationRecords_SupplyId" ON "OperationRecords" ("SupplyId");
CREATE INDEX IF NOT EXISTS "IX_OperationRecords_UserId"   ON "OperationRecords" ("UserId");

-- ============================================================================
-- C. Multicurrency ustunlari
-- ============================================================================
ALTER TABLE "Users"            ADD COLUMN IF NOT EXISTS "SettlementCurrencyId" bigint;
ALTER TABLE "OperationRecords" ADD COLUMN IF NOT EXISTS "CurrencyId"           bigint;
ALTER TABLE "OperationRecords" ADD COLUMN IF NOT EXISTS "Rate"                 numeric NOT NULL DEFAULT 1;

-- Sales: savdo valyutasi (eski savdolar so'mda); foyda/tannarx ustunlari olib tashlanadi.
-- "BaseAmount" — savdoning so'm ekvivalenti (sotuv vaqtidagi kursda muzlatiladi).
ALTER TABLE "Sales"     ADD COLUMN IF NOT EXISTS "CurrencyId" bigint;
ALTER TABLE "Sales"     ADD COLUMN IF NOT EXISTS "BaseAmount" numeric NOT NULL DEFAULT 0;
ALTER TABLE "Sales"     DROP COLUMN IF EXISTS "CostPrice";
ALTER TABLE "Sales"     DROP COLUMN IF EXISTS "BenifitPrice";
ALTER TABLE "SaleItems" DROP COLUMN IF EXISTS "CostPrice";
ALTER TABLE "SaleItems" DROP COLUMN IF EXISTS "Benifit";

-- ============================================================================
-- D. Backfill
-- ============================================================================

-- D1. OperationRecords.UserId — eski yozuvlarda yo'q; Sale/Transaction'dan to'ldiramiz.
UPDATE "OperationRecords" o
SET "UserId" = sa."CustomerId"
FROM "Sales" sa
WHERE sa."OperationRecordId" = o."Id" AND o."UserId" IS NULL;

UPDATE "OperationRecords" o
SET "UserId" = t."UserId"
FROM "Transactions" t
WHERE t."OperationRecordId" = o."Id" AND o."UserId" IS NULL;

-- D2. Har userga asosiy valyuta (rol bo'yicha): Taminotchi/Vositachi -> USD, qolgani -> default.
UPDATE "Users" u
SET "SettlementCurrencyId" = COALESCE(
        CASE WHEN u."Role" IN (1, 4)
             THEN (SELECT "Id" FROM "Currencies" WHERE "Code" = 'USD' LIMIT 1)
        END,
        (SELECT "Id" FROM "Currencies" WHERE "IsDefault" = true LIMIT 1))
WHERE "SettlementCurrencyId" IS NULL;

-- D3. OperationRecords — original valyuta + kurs.
-- D3a. Transaction-bog'liq: eski Amount UZSga konvertatsiyalangan, manbadan tiklaymiz.
UPDATE "OperationRecords" o
SET "CurrencyId" = t."CurrencyId",
    "Rate"       = t."ExchangeRate",
    "Amount"     = CASE WHEN t."IsIncome"
                        THEN t."Amount" + CASE WHEN t."Discount" > 0 AND t."ExchangeRate" <> 0
                                               THEN t."Discount" / t."ExchangeRate" ELSE 0 END
                        ELSE -t."Amount" END
FROM "Transactions" t
WHERE t."OperationRecordId" = o."Id";

-- D3b. Supply-bog'liq: Amount allaqachon original valyutada (eski bazada Supply yo'q — kelajak uchun).
UPDATE "OperationRecords" o
SET "CurrencyId" = s."CurrencyId",
    "Rate"       = 1
FROM "Supplies" s
WHERE o."SupplyId" = s."Id";

-- D3c. Sale-bog'liq: so'mda.
UPDATE "OperationRecords" o
SET "CurrencyId" = (SELECT "Id" FROM "Currencies" WHERE "IsDefault" = true LIMIT 1),
    "Rate"       = 1
FROM "Sales" sa
WHERE sa."OperationRecordId" = o."Id";

-- D3d. Qolgan (bog'lanmagan) yozuvlar -> default valyuta.
UPDATE "OperationRecords"
SET "CurrencyId" = (SELECT "Id" FROM "Currencies" WHERE "IsDefault" = true LIMIT 1)
WHERE "CurrencyId" IS NULL;

-- D4. Eski Sale bug'i: CurrencyId = 0 bo'lgan mijoz hisoblari -> default valyuta.
UPDATE "Accounts"
SET "CurrencyId" = (SELECT "Id" FROM "Currencies" WHERE "IsDefault" = true LIMIT 1)
WHERE "AccountType" = 'Customer' AND "CurrencyId" = 0;

-- D5. Eski savdolar so'mda (default valyuta).
UPDATE "Sales"
SET "CurrencyId" = (SELECT "Id" FROM "Currencies" WHERE "IsDefault" = true LIMIT 1)
WHERE "CurrencyId" IS NULL;

-- D6. Sales.BaseAmount — savdo so'm ekvivalenti (sotuv valyutasi kursida).
--     Eski savdolar uchun tarixiy kurs yo'q -> JORIY kurs (taxminiy, bir martalik backfill).
--     UZS savdolar aniq (kurs 1). Yangi savdolar dastur tomonidan to'g'ri yoziladi.
UPDATE "Sales" s
SET "BaseAmount" = s."TotalAmount" *
    (SELECT CASE WHEN c."IsDefault" OR c."ExchangeRate" = 0 THEN 1 ELSE c."ExchangeRate" END
     FROM "Currencies" c WHERE c."Id" = s."CurrencyId")
WHERE s."BaseAmount" = 0;

-- ============================================================================
-- E. Majburiy qilish + FK + indexlar (multicurrency ustunlari)
-- ============================================================================
ALTER TABLE "OperationRecords" ALTER COLUMN "CurrencyId" SET NOT NULL;
ALTER TABLE "Users"            ALTER COLUMN "SettlementCurrencyId" SET NOT NULL;
ALTER TABLE "Sales"            ALTER COLUMN "CurrencyId" SET NOT NULL;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_OperationRecords_Currencies_CurrencyId') THEN
        ALTER TABLE "OperationRecords"
            ADD CONSTRAINT "FK_OperationRecords_Currencies_CurrencyId"
            FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_Currencies_SettlementCurrencyId') THEN
        ALTER TABLE "Users"
            ADD CONSTRAINT "FK_Users_Currencies_SettlementCurrencyId"
            FOREIGN KEY ("SettlementCurrencyId") REFERENCES "Currencies" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Sales_Currencies_CurrencyId') THEN
        ALTER TABLE "Sales"
            ADD CONSTRAINT "FK_Sales_Currencies_CurrencyId"
            FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_OperationRecords_CurrencyId" ON "OperationRecords" ("CurrencyId");
CREATE INDEX IF NOT EXISTS "IX_Users_SettlementCurrencyId"  ON "Users" ("SettlementCurrencyId");
CREATE INDEX IF NOT EXISTS "IX_Sales_CurrencyId"            ON "Sales" ("CurrencyId");

-- ============================================================================
-- F. Balanslarni qayta qurish (settlement valyutada) — idempotent
-- ============================================================================

-- F1. Har userga settlement hisobi (yo'q bo'lsa ochish).
INSERT INTO "Accounts" ("AccountType", "OpeningBalance", "Discount", "Balance", "CurrencyId", "UserId", "CreatedAt", "IsDeleted")
SELECT 'Customer', 0, 0, 0, u."SettlementCurrencyId", u."Id", now(), false
FROM "Users" u
WHERE NOT EXISTS (
    SELECT 1 FROM "Accounts" a
    WHERE a."AccountType" = 'Customer'
      AND a."UserId" = u."Id"
      AND a."CurrencyId" = u."SettlementCurrencyId");

-- F2. Har yozuvning Rate'ini userning joriy asosiy valyutasiga qayta hisoblash.
--     (derived table — UPDATE FROM ichida target jadvalga JOIN'da murojaat qilib bo'lmaydi)
UPDATE "OperationRecords" o
SET "Rate" = d."NewRate"
FROM (
    SELECT r."Id" AS "Id",
           CASE
               WHEN r."CurrencyId" = u."SettlementCurrencyId" THEN 1
               ELSE COALESCE(NULLIF(t."ExchangeRate", 0), oc."ExchangeRate", 1)
                    / CASE WHEN sc."IsDefault" OR sc."ExchangeRate" = 0 THEN 1 ELSE sc."ExchangeRate" END
           END AS "NewRate"
    FROM "OperationRecords" r
    JOIN "Users" u ON u."Id" = COALESCE(
            r."UserId",
            (SELECT sa."CustomerId" FROM "Sales" sa WHERE sa."OperationRecordId" = r."Id"),
            (SELECT s."UserId"      FROM "Supplies" s WHERE s."Id" = r."SupplyId"))
    JOIN "Currencies" sc ON sc."Id" = u."SettlementCurrencyId"
    JOIN "Currencies" oc ON oc."Id" = r."CurrencyId"
    LEFT JOIN "Transactions" t ON t."OperationRecordId" = r."Id"
) d
WHERE d."Id" = o."Id";

-- F3. Settlement hisoblar balansini qayta qurish.
UPDATE "Accounts" a
SET "Balance" = a."OpeningBalance" + COALESCE((
        SELECT SUM(o."Amount" * o."Rate")
        FROM "OperationRecords" o
        WHERE a."UserId" = COALESCE(
                o."UserId",
                (SELECT sa."CustomerId" FROM "Sales" sa WHERE sa."OperationRecordId" = o."Id"),
                (SELECT s."UserId"      FROM "Supplies" s WHERE s."Id" = o."SupplyId"))
    ), 0)
WHERE a."AccountType" = 'Customer'
  AND EXISTS (
      SELECT 1 FROM "Users" u
      WHERE u."Id" = a."UserId" AND u."SettlementCurrencyId" = a."CurrencyId");

-- F4. Settlement bo'lmagan eski hisoblarni nollash (fantom qarzdor/kreditor bo'lmasin).
UPDATE "Accounts" a
SET "Balance" = 0
WHERE a."AccountType" = 'Customer'
  AND EXISTS (
      SELECT 1 FROM "Users" u
      WHERE u."Id" = a."UserId" AND u."SettlementCurrencyId" <> a."CurrencyId");

-- ============================================================================
-- G. Mahsulot qaytarish (Return / Credit Note) — "Returns"/"ReturnItems"
-- ============================================================================
-- Qaytarish = Sale'ning teskarisi: balansga +TotalAmount (qarz kamayadi),
-- "ProductResidue"."Count" oshadi. "OperationRecords"."Type" uchun Return = 4
-- (INTEGER) — qo'shimcha sxema o'zgarishi YO'Q.

CREATE TABLE IF NOT EXISTS "Returns" (
    "Id"                bigint GENERATED BY DEFAULT AS IDENTITY,
    "Date"              timestamp with time zone NOT NULL,
    "TotalCount"        integer NOT NULL,
    "TotalAmount"       numeric NOT NULL,
    "BaseAmount"        numeric NOT NULL,
    "Note"              text,
    "CurrencyId"        bigint NOT NULL,
    "CustomerId"        bigint NOT NULL,
    "OperationRecordId" bigint NOT NULL,
    "CreatedAt"         timestamp with time zone NOT NULL,
    "CreatedBy"         text,
    "UpdatedAt"         timestamp with time zone,
    "UpdatedBy"         text,
    "IsDeleted"         boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_Returns" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_Returns_OperationRecordId" UNIQUE ("OperationRecordId"),
    CONSTRAINT "FK_Returns_Currencies_CurrencyId"
        FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Returns_Users_CustomerId"
        FOREIGN KEY ("CustomerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Returns_OperationRecords_OperationRecordId"
        FOREIGN KEY ("OperationRecordId") REFERENCES "OperationRecords" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "ReturnItems" (
    "Id"              bigint GENERATED BY DEFAULT AS IDENTITY,
    "BundleCount"     integer NOT NULL,
    "BundleItemCount" integer NOT NULL,
    "TotalCount"      integer NOT NULL,
    "UnitPrice"       numeric NOT NULL,
    "Amount"          numeric NOT NULL,
    "ReturnId"        bigint NOT NULL,
    "ProductTypeId"   bigint NOT NULL,
    "CreatedAt"       timestamp with time zone NOT NULL,
    "CreatedBy"       text,
    "UpdatedAt"       timestamp with time zone,
    "UpdatedBy"       text,
    "IsDeleted"       boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_ReturnItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReturnItems_Returns_ReturnId"
        FOREIGN KEY ("ReturnId") REFERENCES "Returns" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReturnItems_ProductTypes_ProductTypeId"
        FOREIGN KEY ("ProductTypeId") REFERENCES "ProductTypes" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Returns_CurrencyId"        ON "Returns" ("CurrencyId");
CREATE INDEX IF NOT EXISTS "IX_Returns_CustomerId"        ON "Returns" ("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_ReturnItems_ReturnId"      ON "ReturnItems" ("ReturnId");
CREATE INDEX IF NOT EXISTS "IX_ReturnItems_ProductTypeId" ON "ReturnItems" ("ProductTypeId");

COMMIT;
